const TRANSFER_STATES = Object.freeze({
  AVAILABLE: 'AVAILABLE',
  REQUESTED: 'REQUESTED',
  ACCEPTED: 'ACCEPTED',
  READY_FOR_PICKUP: 'READY_FOR_PICKUP',
  READY_FOR_DELIVERY: 'READY_FOR_DELIVERY', // Note: Renamed from OUT_FOR_DELIVERY to match prompt
  TRACKING: 'TRACKING',                   // Renamed from ON_THE_WAY
  APPROACHING: 'APPROACHING',             // New state
  ARRIVED: 'ARRIVED',
  HANDOVER_READY: 'HANDOVER_READY',       // Renamed from HANDOVER_PENDING
  QR_VERIFIED: 'QR_VERIFIED',             // Renamed from RECEIVED
  RECEIVER_CONFIRMED: 'RECEIVER_CONFIRMED',// New state
  COMPLETED: 'COMPLETED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
});

const TRANSFER_FLOW = Object.freeze({
  [TRANSFER_STATES.AVAILABLE]: [TRANSFER_STATES.REQUESTED, TRANSFER_STATES.CANCELLED, TRANSFER_STATES.EXPIRED],
  [TRANSFER_STATES.REQUESTED]: [TRANSFER_STATES.ACCEPTED, TRANSFER_STATES.REJECTED, TRANSFER_STATES.CANCELLED, TRANSFER_STATES.EXPIRED],
  [TRANSFER_STATES.ACCEPTED]: [TRANSFER_STATES.READY_FOR_PICKUP, TRANSFER_STATES.READY_FOR_DELIVERY, TRANSFER_STATES.CANCELLED, TRANSFER_STATES.EXPIRED],
  [TRANSFER_STATES.READY_FOR_PICKUP]: [TRANSFER_STATES.TRACKING, TRANSFER_STATES.ARRIVED, TRANSFER_STATES.HANDOVER_READY, TRANSFER_STATES.CANCELLED, TRANSFER_STATES.EXPIRED],
  [TRANSFER_STATES.READY_FOR_DELIVERY]: [TRANSFER_STATES.TRACKING, TRANSFER_STATES.ARRIVED, TRANSFER_STATES.HANDOVER_READY, TRANSFER_STATES.CANCELLED, TRANSFER_STATES.EXPIRED],
  [TRANSFER_STATES.TRACKING]: [TRANSFER_STATES.APPROACHING, TRANSFER_STATES.ARRIVED, TRANSFER_STATES.HANDOVER_READY, TRANSFER_STATES.CANCELLED],
  [TRANSFER_STATES.APPROACHING]: [TRANSFER_STATES.ARRIVED, TRANSFER_STATES.HANDOVER_READY, TRANSFER_STATES.CANCELLED],
  [TRANSFER_STATES.ARRIVED]: [TRANSFER_STATES.HANDOVER_READY, TRANSFER_STATES.CANCELLED],
  [TRANSFER_STATES.HANDOVER_READY]: [TRANSFER_STATES.QR_VERIFIED, TRANSFER_STATES.RECEIVER_CONFIRMED, TRANSFER_STATES.COMPLETED, TRANSFER_STATES.CANCELLED],
  [TRANSFER_STATES.QR_VERIFIED]: [TRANSFER_STATES.RECEIVER_CONFIRMED, TRANSFER_STATES.COMPLETED, TRANSFER_STATES.CANCELLED],
  [TRANSFER_STATES.RECEIVER_CONFIRMED]: [TRANSFER_STATES.COMPLETED, TRANSFER_STATES.CANCELLED],
  [TRANSFER_STATES.COMPLETED]: [],
  [TRANSFER_STATES.REJECTED]: [],
  [TRANSFER_STATES.CANCELLED]: [],
  [TRANSFER_STATES.EXPIRED]: [],
});

const assertValidTransition = (currentStatus, targetStatus) => {
  const allowed = TRANSFER_FLOW[currentStatus] || [];
  if (!allowed.includes(targetStatus)) {
    throw new Error(`Invalid state transition from ${currentStatus} to ${targetStatus}`);
  }
  return true;
};

module.exports = {
  TRANSFER_STATES,
  TRANSFER_FLOW,
  assertValidTransition,
};
